# -*- coding: utf-8 -*-
"""DL_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YSoVWBv1FPO70HeGoMw7fho6oS8XEpTG
"""

! pip install torch torchvision opencv-python

! git clone https://github.com/ultralytics/yolov5
! cd yolov5 && pip install -r requirements.txt

import torch
import cv2

# Load Yolov5 model (pretrained on COCO dataset)
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained = True)

# Load image
img_path = "/content/data1.jpg"
img = cv2.imread(img_path)

# Perform object detection
results = model(img)

# Display results
results.show()

# Save results
results.save('output/')

# Optionally to get more details such as confidence sores, bounding boxes, object classes
df = results.pandas().xyxy[0]
print(df)